// <auto-generated />
using System;
using ClinicSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicSystem.Migrations
{
    [DbContext(typeof(DbContainer))]
    [Migration("20220305180448_Clinic11")]
    partial class Clinic11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClinicSystem.Entities.AppointmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppointmentTypeName")
                        .HasMaxLength(100);

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("AppointmentType");
                });

            modelBuilder.Entity("ClinicSystem.Entities.CheifComplaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheifComplaintExplaination")
                        .HasMaxLength(10000);

                    b.Property<string>("Note")
                        .HasMaxLength(10000);

                    b.Property<int>("PatientProcessId");

                    b.HasKey("Id");

                    b.HasIndex("PatientProcessId")
                        .IsUnique();

                    b.ToTable("CheifComplaint");
                });

            modelBuilder.Entity("ClinicSystem.Entities.Drugs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dose")
                        .HasMaxLength(1000);

                    b.Property<string>("DrugName")
                        .HasMaxLength(1000);

                    b.Property<int>("PatientProcessId");

                    b.HasKey("Id");

                    b.HasIndex("PatientProcessId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("ClinicSystem.Entities.Followup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("ExaminationId");

                    b.Property<int?>("FollowupId");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("ExaminationId")
                        .IsUnique();

                    b.HasIndex("FollowupId")
                        .IsUnique()
                        .HasFilter("[FollowupId] IS NOT NULL");

                    b.ToTable("Followup");
                });

            modelBuilder.Entity("ClinicSystem.Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenderName")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("ClinicSystem.Entities.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InsuranceName")
                        .HasMaxLength(200);

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("Insurance");
                });

            modelBuilder.Entity("ClinicSystem.Entities.InsurancePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("ExaminationPaidByInsurance")
                        .HasColumnType("money");

                    b.Property<decimal?>("ExaminationPaidByPatient")
                        .HasColumnType("money");

                    b.Property<decimal?>("ExaminationTotalPrice")
                        .HasColumnType("money");

                    b.Property<decimal?>("FollowupPaidByInsurance")
                        .HasColumnType("money");

                    b.Property<decimal?>("FollowupPaidByPatient")
                        .HasColumnType("money");

                    b.Property<decimal?>("FollowupTotalPrice")
                        .HasColumnType("money");

                    b.Property<int>("InsuranceId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("PackageName")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsurancePackage");
                });

            modelBuilder.Entity("ClinicSystem.Entities.InsurancePackageOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InsurancePackageId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OperationId");

                    b.Property<decimal?>("PaidByInsurance")
                        .HasColumnType("money");

                    b.Property<decimal?>("PaidByPatient")
                        .HasColumnType("money");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePackageId");

                    b.HasIndex("OperationId");

                    b.ToTable("insurancePackageOperation");
                });

            modelBuilder.Entity("ClinicSystem.Entities.LaboratoryInvestigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InvestigationName")
                        .HasMaxLength(500);

                    b.Property<string>("InvestigationNote")
                        .HasMaxLength(10000);

                    b.Property<int>("PatientProcessId");

                    b.Property<string>("ResultNote")
                        .HasMaxLength(10000);

                    b.Property<string>("SuggestedLaboratory")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("PatientProcessId");

                    b.ToTable("LaboratoryInvestigation");
                });

            modelBuilder.Entity("ClinicSystem.Entities.MedicalDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiagnosisExplaination")
                        .HasMaxLength(10000);

                    b.Property<string>("Note")
                        .HasMaxLength(10000);

                    b.Property<int>("PatientProcessId");

                    b.HasKey("Id");

                    b.HasIndex("PatientProcessId");

                    b.ToTable("MedicalDiagnosis");
                });

            modelBuilder.Entity("ClinicSystem.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MedicalHistoryNotice")
                        .HasMaxLength(10000);

                    b.Property<string>("Note")
                        .HasMaxLength(10000);

                    b.Property<int>("PatientProfileId");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.ToTable("MedicalHistory");
                });

            modelBuilder.Entity("ClinicSystem.Entities.MedicineHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date");

                    b.Property<string>("MedicineName")
                        .HasMaxLength(300);

                    b.Property<string>("Note")
                        .HasMaxLength(10000);

                    b.Property<int>("PatientProfileId");

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.ToTable("MedicineHistory");
                });

            modelBuilder.Entity("ClinicSystem.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("OperationName")
                        .HasMaxLength(500);

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Operation");
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DoctorId");

                    b.Property<DateTime?>("FollowupAppointment");

                    b.Property<float>("InsuranceDiscount");

                    b.Property<int?>("InsurancePackageId");

                    b.Property<decimal?>("OperationActualPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("OriginalTotal")
                        .HasColumnType("money");

                    b.Property<int>("PatientProfileId");

                    b.Property<DateTime>("ProcessDateTime");

                    b.Property<decimal>("ProcessOriginalPrice")
                        .HasColumnType("money");

                    b.Property<int>("ProcessTypeId");

                    b.Property<decimal>("TotalAfterDiscount")
                        .HasColumnType("money");

                    b.Property<string>("extendidentityuserId");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePackageId");

                    b.HasIndex("PatientProfileId");

                    b.HasIndex("ProcessTypeId");

                    b.HasIndex("extendidentityuserId");

                    b.ToTable("PatientProcess");
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProcessOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DoctorId");

                    b.Property<string>("Note")
                        .HasMaxLength(10000);

                    b.Property<int>("OperationId");

                    b.Property<int>("OperationOriginalPrice");

                    b.Property<int>("OperationPriceAfterDiscount");

                    b.Property<int>("PatientProcessId");

                    b.Property<string>("extendidentityuserId");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("PatientProcessId");

                    b.HasIndex("extendidentityuserId");

                    b.ToTable("PatientProcessOperation");
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<int>("GenderId");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("PatientProfile");
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProfileInsurancePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<int>("InsurancePackageId");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("PatientProfileId");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePackageId");

                    b.HasIndex("PatientProfileId");

                    b.ToTable("PatientProfileInsurancePackage");
                });

            modelBuilder.Entity("ClinicSystem.Entities.PreAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AppointmentDateTime");

                    b.Property<int>("AppointmentTypeId");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("money");

                    b.Property<string>("DoctorId");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100);

                    b.Property<string>("Notes")
                        .HasMaxLength(2000);

                    b.Property<int?>("PatientProcessId");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.Property<int>("ProcessTypeId");

                    b.Property<string>("extendidentityuserId");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTypeId");

                    b.HasIndex("PatientProcessId")
                        .IsUnique()
                        .HasFilter("[PatientProcessId] IS NOT NULL");

                    b.HasIndex("ProcessTypeId");

                    b.HasIndex("extendidentityuserId");

                    b.ToTable("PreAppointment");
                });

            modelBuilder.Entity("ClinicSystem.Entities.ProcessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProcessName")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ProcessType");
                });

            modelBuilder.Entity("ClinicSystem.Entities.RadioGraphicExamination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExaminationName")
                        .HasMaxLength(500);

                    b.Property<string>("ExaminationNote")
                        .HasMaxLength(10000);

                    b.Property<int>("PatientProcessId");

                    b.Property<string>("ResultNote")
                        .HasMaxLength(10000);

                    b.Property<string>("SuggestedLaboratory")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("PatientProcessId");

                    b.ToTable("RadioGraphicExamination");
                });

            modelBuilder.Entity("ClinicSystem.Entities.Setup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsSetup");

                    b.HasKey("Id");

                    b.ToTable("Setup");
                });

            modelBuilder.Entity("ClinicSystem.Entities.SurgeryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Note")
                        .HasMaxLength(10000);

                    b.Property<int>("PatientProfileId");

                    b.Property<string>("SurgeryName")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("PatientProfileId");

                    b.ToTable("SurgeryHistory");
                });

            modelBuilder.Entity("ClinicSystem.Entities.WorkingTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Day");

                    b.Property<string>("DayName");

                    b.Property<string>("ExtenIdentityUserId");

                    b.Property<string>("extendIdentityUserId");

                    b.Property<DateTime>("from");

                    b.Property<DateTime>("to");

                    b.HasKey("Id");

                    b.HasIndex("extendIdentityUserId");

                    b.ToTable("workingTime");
                });

            modelBuilder.Entity("ClinicSystem.Privilage.ExtendIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<bool>("Active");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<int?>("ExaminationTime");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("MiddleName");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ClinicSystem.Entities.CheifComplaint", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProcess", "patientProcess")
                        .WithOne("cheifComplaint")
                        .HasForeignKey("ClinicSystem.Entities.CheifComplaint", "PatientProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.Drugs", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProcess", "patientProcess")
                        .WithMany("drugs")
                        .HasForeignKey("PatientProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.Followup", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProcess", "Examination")
                        .WithOne("followupE")
                        .HasForeignKey("ClinicSystem.Entities.Followup", "ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Entities.PatientProcess", "Followupp")
                        .WithOne("followupF")
                        .HasForeignKey("ClinicSystem.Entities.Followup", "FollowupId");
                });

            modelBuilder.Entity("ClinicSystem.Entities.InsurancePackage", b =>
                {
                    b.HasOne("ClinicSystem.Entities.Insurance", "insurance")
                        .WithMany("insurancePackages")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.InsurancePackageOperation", b =>
                {
                    b.HasOne("ClinicSystem.Entities.InsurancePackage", "insurancePackage")
                        .WithMany("insurancePackageOperation")
                        .HasForeignKey("InsurancePackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Entities.Operation", "operation")
                        .WithMany("insurancePackageOperation")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.LaboratoryInvestigation", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProcess", "patientProcess")
                        .WithMany("laboratoryInvestigations")
                        .HasForeignKey("PatientProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.MedicalDiagnosis", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProcess", "patientProcess")
                        .WithMany("diagnoses")
                        .HasForeignKey("PatientProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.MedicalHistory", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProfile", "patientProfile")
                        .WithMany("medicalHistories")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.MedicineHistory", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProfile", "patientProfile")
                        .WithMany("medicineHistories")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProcess", b =>
                {
                    b.HasOne("ClinicSystem.Entities.InsurancePackage", "insurancePackage")
                        .WithMany("patientProcesses")
                        .HasForeignKey("InsurancePackageId");

                    b.HasOne("ClinicSystem.Entities.PatientProfile", "patient")
                        .WithMany("patientProcesses")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Entities.ProcessType", "processType")
                        .WithMany("patientProcesses")
                        .HasForeignKey("ProcessTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser", "extendidentityuser")
                        .WithMany()
                        .HasForeignKey("extendidentityuserId");
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProcessOperation", b =>
                {
                    b.HasOne("ClinicSystem.Entities.Operation", "operation")
                        .WithMany("patientProcessOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Entities.PatientProcess", "patientProcess")
                        .WithMany("patientProcessOperations")
                        .HasForeignKey("PatientProcessId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser", "extendidentityuser")
                        .WithMany()
                        .HasForeignKey("extendidentityuserId");
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProfile", b =>
                {
                    b.HasOne("ClinicSystem.Entities.Gender", "gender")
                        .WithMany("patientProfiles")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.PatientProfileInsurancePackage", b =>
                {
                    b.HasOne("ClinicSystem.Entities.InsurancePackage", "insurnacePackage")
                        .WithMany("patientProfileInsurancePackages")
                        .HasForeignKey("InsurancePackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Entities.PatientProfile", "patientProfile")
                        .WithMany("patientProfileInsurancePackages")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.PreAppointment", b =>
                {
                    b.HasOne("ClinicSystem.Entities.AppointmentType", "appointmentType")
                        .WithMany("preAppointments")
                        .HasForeignKey("AppointmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Entities.PatientProcess", "patientProcess")
                        .WithOne("preAppointment")
                        .HasForeignKey("ClinicSystem.Entities.PreAppointment", "PatientProcessId");

                    b.HasOne("ClinicSystem.Entities.ProcessType", "processType")
                        .WithMany("preAppointments")
                        .HasForeignKey("ProcessTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser", "extendidentityuser")
                        .WithMany()
                        .HasForeignKey("extendidentityuserId");
                });

            modelBuilder.Entity("ClinicSystem.Entities.RadioGraphicExamination", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProcess", "patientProcess")
                        .WithMany("radioGraphicExaminations")
                        .HasForeignKey("PatientProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.SurgeryHistory", b =>
                {
                    b.HasOne("ClinicSystem.Entities.PatientProfile", "patientProfile")
                        .WithMany("surgeryHistories")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ClinicSystem.Entities.WorkingTime", b =>
                {
                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser", "extendIdentityUser")
                        .WithMany()
                        .HasForeignKey("extendIdentityUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicSystem.Privilage.ExtendIdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
